### ISSUE TITLE
saving to png outside jupyter

### ISSUE THREAD

**Issue by keithbriggs** [ricklupton/floweaver#64] opened 2018-11-06 09:49 UTC
I cannot see any way in the docs to save the diagram to png when not using jupyter.

fw.weave(sdd,flows).to_widget(**size).auto_save_png('foo_floweaver.png')

runs but does not save any figure.  Is this possible?

**Comment by ricklupton** [comment] 2018-11-26 21:06
Duplicate of #34, please see discussion there -- it is possible and it's on the roadmap to make it easier.

**Closed by ricklupton** 2018-11-26 21:06 UTC
