### ISSUE TITLE
Floweaver/ipysankeywidget rendering in JupyterLab

### ISSUE THREAD

**Issue by PhilCHC** [ricklupton/floweaver#80] opened 2019-05-02 06:11 UTC
Love the library, I wish I could get it to work in JupyterLab

**Comment by ricklupton** [comment] 2019-05-22 13:12
Hi, thanks :) It'd be great to get it working in JupyterLab, I just haven't had the time to try yet. Help here is welcome, if anyone is interested!

Closing as duplicate of https://github.com/ricklupton/ipysankeywidget/issues/36

**Closed by ricklupton** 2019-05-22 13:12 UTC
