### ISSUE TITLE
Add Silent export to SVG and PNG that does not rely on displaying

### ISSUE THREAD

**Issue by ELC** [ricklupton/floweaver#61] opened 2018-09-13 17:52 UTC
When using the `auto_save_png` and `auto_save_svg` the image is only saved when it is displayed in the notebook. If a `;` is added to that line to avoid showing duplicates (in case both svg and png are requested), the image with the `;` is not generated.

I believe it should be a default feature to first save and then show the image in the notebook instead of saving only when is displayed. This would also allow generating images without explicitly opening the notebook (through nbconvert for example).

**Comment by ricklupton** [comment] 2018-09-13 20:10
I think this is a duplicate of #34. It's not possible to save first because the Sankey diagram is actually drawn in the browser, then sent back to Python to be saved. See #34 for some other options for saving images.

**Closed by ricklupton** 2018-09-13 20:10 UTC
